%% UNIPLU-BR Station Panel - Interactive Hydroclimatic Dashboard
% Purpose:
%   Interactive MATLAB interface for exploratory hydroclimatic analysis using
%   monthly rainfall products generated by the Python preprocessing pipeline.
%
% Inputs:
%   - MAT file containing monthly rainfall fields:
%     gauge_code, year, month, rain_mm, lat, long, city, state.
%
% Outputs:
%   - Spatial annual precipitation heatmaps (statewide mode).
%   - Monthly availability matrix (present vs missing records).
%   - Monthly hyetograph and annual anomaly visualization.
%   - Mann-Kendall trend inference with Sen slope via ktaub.
%
% Scientific rationale:
%   This script is designed for post-QC data inspection. It assumes Python
%   preprocessing has already removed low-quality months to reduce false dry
%   period interpretation caused by missing daily observations.
%
% Notes:
%   - Requires ktaub.m to be available in MATLAB path.
%   - Reads dados_hidro_br_mensal_real.mat first when available.

clear; clc; close all;

set(groot, 'defaultFigureColor', 'w', 'defaultAxesColor', 'w', ...
  'defaultAxesXColor', 'k', 'defaultAxesYColor', 'k', 'defaultTextColor', 'k');

scriptDir = fileparts(mfilename('fullpath'));
projectRoot = fileparts(fileparts(scriptDir));

matCandidates = {
  fullfile(projectRoot, 'outputs', 'dados_hidro_br_mensal_real.mat')
  fullfile(projectRoot, 'dados_hidro_br_mensal_real.mat')
  fullfile(projectRoot, 'outputs', 'dados_hidro_br_mensal.mat')
  fullfile(projectRoot, 'dados_hidro_br_mensal.mat')
  'dados_hidro_br_mensal_real.mat'
  'dados_hidro_br_mensal.mat'
  };

[dataTbl, sourceMat] = loadUnipluMonthlyData(matCandidates);
dataTbl = cleanInputTable(dataTbl);

if isempty(dataTbl)
  error('No valid rows found after cleaning input data.');
end

availableYears = sort(unique(dataTbl.year));
if isempty(availableYears)
  error('Dataset has no valid years.');
end

introText = sprintf(['UNIPLU-BR HYDROCLIMATIC ANALYSIS PANEL\n\n', ...
  'Loaded MAT file:\n%s\n\n', ...
  'Available period: %d - %d\n\n', ...
  'Modules:\n', ...
  '[1] Spatial Distribution Maps\n', ...
  '[2] Time Series Analysis\n', ...
  '    - annual hyetograph\n', ...
  '    - anomaly chart\n', ...
  '    - 5-year low-pass filter\n', ...
  '    - Mann-Kendall + Sen slope\n'], ...
  sourceMat, min(availableYears), max(availableYears));
uiwait(msgbox(introText, 'UNIPLU-BR Tool Overview', 'help'));

menuOptions = {
  '[1] Spatial Distribution Maps'
  '[2] Time Series Analysis'
  };

[idxMain, isConfirmed] = listdlg( ...
  'PromptString', 'Select analysis module:', ...
  'SelectionMode', 'single', ...
  'ListString', menuOptions, ...
  'Name', 'Main Menu', ...
  'ListSize', [460, 120]);

if ~isConfirmed || isempty(idxMain)
  disp('Session terminated by user.');
  return;
end

switch idxMain
  case 1
    runSpatialDistributionModule(dataTbl);
  case 2
    runTimeSeriesModule(dataTbl);
end


function runSpatialDistributionModule(dataTbl)
%RUNSPATIALDISTRIBUTIONMODULE Generate statewide annual precipitation maps.
% Inputs:
%   dataTbl - cleaned monthly table with columns including state/year/rain_mm.
% Output:
%   Figure with one interpolated map per year and a textual summary report.

states = sort(unique(dataTbl.state));

[idxState, okState] = listdlg( ...
  'PromptString', 'Select ONE STATE:', ...
  'SelectionMode', 'single', ...
  'ListString', cellstr(states), ...
  'Name', 'State Selection', ...
  'ListSize', [300, 420]);

if ~okState || isempty(idxState)
  return;
end

selectedState = states(idxState);
stateData = dataTbl(dataTbl.state == selectedState, :);

availableYears = sort(unique(stateData.year));
if isempty(availableYears)
  errordlg('No years available for selected state.', 'Data Error');
  return;
end

[idxStart, okStart] = listdlg( ...
  'PromptString', 'Select START YEAR:', ...
  'SelectionMode', 'single', ...
  'ListString', cellstr(string(availableYears)), ...
  'Name', 'Temporal Window Setup');

if ~okStart || isempty(idxStart)
  return;
end

startYear = availableYears(idxStart);
endCandidates = availableYears(availableYears >= startYear);

[idxEnd, okEnd] = listdlg( ...
  'PromptString', 'Select END YEAR:', ...
  'SelectionMode', 'single', ...
  'ListString', cellstr(string(endCandidates)), ...
  'Name', 'Temporal Window Setup');

if ~okEnd || isempty(idxEnd)
  return;
end

endYear = endCandidates(idxEnd);
selectedYears = startYear:endYear;

figure('Name', sprintf('Spatial Distribution Maps - %s', selectedState), ...
  'Position', [100, 100, 1200, 720]);
tiledlayout('flow', 'TileSpacing', 'compact', 'Padding', 'compact');

reportText = sprintf('--- ANNUAL PRECIPITATION REPORT ---\n\n');

for i = 1:numel(selectedYears)
  thisYear = selectedYears(i);
  yearData = stateData(stateData.year == thisYear, :);

  % Annual total is accepted only when at least 10 monthly values exist,
  % reducing annual bias caused by sparse station-year records.
  stationYear = aggregateAnnualStationYear(yearData, 10);
  stationYear = stationYear(~isnan(stationYear.annual_total), :);

  if isempty(stationYear)
    reportText = [reportText, sprintf('YEAR %d:\n', thisYear)]; %#ok<AGROW>
    reportText = [reportText, sprintf('  State Average: n/a\n')]; %#ok<AGROW>
    reportText = [reportText, sprintf('  Rainiest Station: n/a\n')]; %#ok<AGROW>
    reportText = [reportText, sprintf('  Driest Station: n/a\n\n')]; %#ok<AGROW>

    ax = nexttile;
    axis(ax, 'off');
    text(ax, 0.5, 0.5, sprintf('%d\nNo valid annual totals', thisYear), ...
      'HorizontalAlignment', 'center', 'FontWeight', 'bold');
    continue;
  end

  [maxRain, maxIdx] = max(stationYear.annual_total);
  [minRain, minIdx] = min(stationYear.annual_total);
  meanRain = mean(stationYear.annual_total, 'omitnan');

  wetLabel = sprintf('%s (%s)', stationYear.city(maxIdx), stationYear.gauge_code(maxIdx));
  dryLabel = sprintf('%s (%s)', stationYear.city(minIdx), stationYear.gauge_code(minIdx));

  reportText = [reportText, sprintf('YEAR %d:\n', thisYear)]; %#ok<AGROW>
  reportText = [reportText, sprintf('  State Average: %.1f mm\n', meanRain)]; %#ok<AGROW>
  reportText = [reportText, sprintf('  Rainiest Station: %s (%.1f mm)\n', wetLabel, maxRain)]; %#ok<AGROW>
  reportText = [reportText, sprintf('  Driest Station: %s (%.1f mm)\n\n', dryLabel, minRain)]; %#ok<AGROW>

  ax = nexttile;
  drawAnnualSpatialMap(ax, stationYear, thisYear);
end

cb = colorbar;
cb.Layout.Tile = 'east';
cb.Label.String = 'Annual Total Precipitation (mm)';

uiwait(msgbox(reportText, 'Tangible Data: Maps Summary', 'help'));
end


function runTimeSeriesModule(dataTbl)
%RUNTIMESERIESMODULE Build annual, anomaly, and trend diagnostics.
% Inputs:
%   dataTbl - cleaned monthly table.
% Outputs:
%   Figure with annual hyetograph, anomaly panel, low-pass signal, optional
%   availability matrix, and textual summary including Mann-Kendall metrics.

states = sort(unique(dataTbl.state));
[idxState, okState] = listdlg( ...
  'PromptString', 'Select ONE STATE:', ...
  'SelectionMode', 'single', ...
  'ListString', cellstr(states), ...
  'Name', 'State Selection', ...
  'ListSize', [300, 420]);

if ~okState || isempty(idxState)
  return;
end

selectedState = states(idxState);
stateData = dataTbl(dataTbl.state == selectedState, :);

scopeChoice = questdlg('Choose analysis scope:', ...
  'Analysis Scope', ...
  'Statewide (Aggregated)', ...
  'Specific Station', ...
  'Statewide (Aggregated)');

if isempty(scopeChoice)
  return;
end

selectedGauge = "";
selectedLabel = "";
scopeData = stateData;

if strcmp(scopeChoice, 'Specific Station')
  stationMeta = unique(stateData(:, {'gauge_code', 'city'}), 'rows');
  stationLabels = stationMeta.city + " | " + stationMeta.gauge_code;

  [idxStation, okStation] = listdlg( ...
    'PromptString', 'Select ONE STATION:', ...
    'SelectionMode', 'single', ...
    'ListString', cellstr(stationLabels), ...
    'Name', 'Station Selection', ...
    'ListSize', [460, 420]);

  if ~okStation || isempty(idxStation)
    return;
  end

  selectedGauge = stationMeta.gauge_code(idxStation);
  selectedLabel = stationLabels(idxStation);
  scopeData = stateData(stateData.gauge_code == selectedGauge, :);
end

validYears = sort(unique(scopeData.year));
if isempty(validYears)
  errordlg('No years available for selected scope.', 'Data Error');
  return;
end

[idxStart, okStart] = listdlg( ...
  'PromptString', 'Select START YEAR:', ...
  'SelectionMode', 'single', ...
  'ListString', cellstr(string(validYears)), ...
  'Name', 'Time Period');

if ~okStart || isempty(idxStart)
  return;
end

startYear = validYears(idxStart);
endCandidates = validYears(validYears >= startYear);

[idxEnd, okEnd] = listdlg( ...
  'PromptString', 'Select END YEAR:', ...
  'SelectionMode', 'single', ...
  'ListString', cellstr(string(endCandidates)), ...
  'Name', 'Time Period');

if ~okEnd || isempty(idxEnd)
  return;
end

endYear = endCandidates(idxEnd);
periodData = scopeData(scopeData.year >= startYear & scopeData.year <= endYear, :);

if isempty(periodData)
  errordlg('No data found for selected period.', 'Data Error');
  return;
end

yearsVec = (startYear:endYear)';
% The monthly dataset is expected to be pre-filtered by Python with the
% strict 10% missing-data tolerance rule; annual values are then computed on
% this quality-controlled baseline.
annualByStation = aggregateAnnualStationYear(periodData, 10);

if strcmp(scopeChoice, 'Statewide (Aggregated)')
  annualTotals = nan(size(yearsVec));
  for i = 1:numel(yearsVec)
    y = yearsVec(i);
    vals = annualByStation.annual_total(annualByStation.year == y);
    if ~isempty(vals)
      % Statewide annual signal is computed as the mean of valid station-year
      % annual totals, avoiding overweighting dense subregions.
      annualTotals(i) = mean(vals, 'omitnan');
    end
  end
  baseTitle = "Statewide Aggregated - " + selectedState;
else
  annualTotals = nan(size(yearsVec));
  stationAnnual = annualByStation(annualByStation.gauge_code == selectedGauge, :);
  [tf, pos] = ismember(stationAnnual.year, yearsVec);
  annualTotals(pos(tf)) = stationAnnual.annual_total(tf);
  baseTitle = "Station " + selectedLabel;
end

longTermMean = mean(annualTotals, 'omitnan');
anomalies = annualTotals - longTermMean;
movingAvg = movmean(annualTotals, 5, 'omitnan');

valid = ~isnan(annualTotals);
[pValue, senSlope, trendLabel] = runKtaubSafe(yearsVec(valid), annualTotals(valid));

figure('Name', 'Time Series & Statistical Analysis', 'Position', [130, 100, 1000, 900]);
tiledlayout(3, 1, 'TileSpacing', 'compact', 'Padding', 'compact');

ax1 = nexttile;
bar(ax1, yearsVec, annualTotals, 'FaceColor', [0.60 0.80 0.90], 'EdgeColor', 'none');
hold(ax1, 'on');
yline(ax1, longTermMean, 'k--', 'LTM', 'LineWidth', 1.4, 'LabelHorizontalAlignment', 'left');

if sum(valid) >= 2
  pfit = polyfit(yearsVec(valid), annualTotals(valid), 1);
  plot(ax1, yearsVec, polyval(pfit, yearsVec), 'r-', 'LineWidth', 1.5);
  legend(ax1, {'Annual Total', 'LTM', 'Linear Trend'}, 'Location', 'best');
else
  legend(ax1, {'Annual Total', 'LTM'}, 'Location', 'best');
end

title(ax1, sprintf('Annual Hyetograph | Kendall p-value = %s | Sen slope = %s mm/year', ...
  formatMetric(pValue), formatMetric(senSlope)));
ylabel(ax1, 'Precipitation (mm)');
grid(ax1, 'on');

ax2 = nexttile;
b = bar(ax2, yearsVec, anomalies, 'FaceColor', 'flat', 'EdgeColor', 'none');
posMask = anomalies >= 0;
negMask = anomalies < 0;
b.CData(posMask, :) = repmat([0.20 0.60 0.85], sum(posMask), 1);
b.CData(negMask, :) = repmat([0.85 0.30 0.30], sum(negMask), 1);
title(ax2, 'Precipitation Anomalies (Annual Total - LTM)');
ylabel(ax2, '\Delta Precipitation (mm)');
grid(ax2, 'on');

ax3 = nexttile;
plot(ax3, yearsVec, annualTotals, '-.', 'Color', [0.65 0.65 0.65], 'LineWidth', 1.2);
hold(ax3, 'on');
plot(ax3, yearsVec, movingAvg, 'k-', 'LineWidth', 2);
title(ax3, 'Low-Pass Filter (5-Year Moving Average)');
xlabel(ax3, 'Year');
ylabel(ax3, 'Precipitation (mm)');
legend(ax3, {'Original Signal', '5-year Moving Average'}, 'Location', 'best');
grid(ax3, 'on');

linkaxes([ax1, ax2, ax3], 'x');
xlim(ax1, [startYear - 0.5, endYear + 0.5]);

[maxAnnual, idxMax] = max(annualTotals);
[minAnnual, idxMin] = min(annualTotals);

if isempty(idxMax) || isnan(maxAnnual)
  wettestYearText = 'n/a';
else
  wettestYearText = sprintf('%d (%.1f mm)', yearsVec(idxMax), maxAnnual);
end

if isempty(idxMin) || isnan(minAnnual)
  driestYearText = 'n/a';
else
  driestYearText = sprintf('%d (%.1f mm)', yearsVec(idxMin), minAnnual);
end

reportText = sprintf('--- TIME SERIES REPORT ---\nPeriod: %d to %d\n\n', startYear, endYear);
reportText = [reportText, sprintf('Scope: %s\n', baseTitle)]; %#ok<AGROW>
reportText = [reportText, sprintf('Long-Term Mean (LTM): %s mm\n', formatMetric(longTermMean))]; %#ok<AGROW>
reportText = [reportText, sprintf('Wettest Year: %s\n', wettestYearText)]; %#ok<AGROW>
reportText = [reportText, sprintf('Driest Year: %s\n', driestYearText)]; %#ok<AGROW>
reportText = [reportText, sprintf('Kendall p-value: %s\n', formatMetric(pValue))]; %#ok<AGROW>
reportText = [reportText, sprintf('Sen slope: %s mm/year\n', formatMetric(senSlope))]; %#ok<AGROW>
reportText = [reportText, sprintf('Trend Interpretation: %s\n', trendLabel)]; %#ok<AGROW>

uiwait(msgbox(reportText, 'Tangible Data: Time Series Summary', 'help'));

if strcmp(scopeChoice, 'Specific Station')
  [availability, availYears] = buildMonthlyAvailability(scopeData, startYear, endYear);

  figure('Name', 'Monthly Availability Heatmap', 'Position', [180, 150, 920, 430]);
  imagesc(availYears, 1:12, availability);
  set(gca, 'YDir', 'normal');
  yticks(1:12);
  yticklabels({'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'});
  xlabel('Year');
  ylabel('Month');
  title(sprintf('Data Availability (Present vs Missing) - %s', selectedLabel), 'Interpreter', 'none');
  colormap(gca, [0.85 0.35 0.35; 0.25 0.65 0.35]);
  caxis([0 1]);
  cb = colorbar;
  cb.Ticks = [0, 1];
  cb.TickLabels = {'Missing', 'Present'};
  grid on;
end
end


function drawAnnualSpatialMap(ax, stationYear, thisYear)
%DRAWANNUALSPATIALMAP Render interpolation-based annual precipitation heatmap.
% Inputs:
%   ax - destination axes.
%   stationYear - table with lon/lat/annual_total for one year.
%   thisYear - scalar year label for title.

lon = stationYear.lon;
lat = stationYear.lat;
z = stationYear.annual_total;

maskValid = ~isnan(lon) & ~isnan(lat) & ~isnan(z);
lonValid = lon(maskValid);
latValid = lat(maskValid);
zValid = z(maskValid);

if numel(zValid) < 3 || numel(unique(lonValid)) < 2 || numel(unique(latValid)) < 2
  scatter(ax, lonValid, latValid, 60, zValid, 'filled', 'MarkerEdgeColor', 'k');
  title(ax, sprintf('%d (insufficient points for interpolation)', thisYear));
  xlabel(ax, 'Longitude');
  ylabel(ax, 'Latitude');
  grid(ax, 'on');
  axis(ax, 'tight');
  return;
end

lonMin = min(lonValid); lonMax = max(lonValid);
latMin = min(latValid); latMax = max(latValid);
padLon = max((lonMax - lonMin) * 0.08, 0.05);
padLat = max((latMax - latMin) * 0.08, 0.05);

xq = linspace(lonMin - padLon, lonMax + padLon, 120);
yq = linspace(latMin - padLat, latMax + padLat, 120);
[lonGrid, latGrid] = meshgrid(xq, yq);

F = scatteredInterpolant(lonValid, latValid, zValid, 'natural', 'none');
Z = F(lonGrid, latGrid);

% Restrict interpolation domain to convex hull to avoid extrapolation artifacts
% where no gauges exist.
if numel(lonValid) >= 3
  try
    hullIdx = convhull(lonValid, latValid);
    inMask = inpolygon(lonGrid, latGrid, lonValid(hullIdx), latValid(hullIdx));
    Z(~inMask) = NaN;
  catch
    % Fallback keeps interpolation surface when hull estimation fails.
  end
end

contourf(ax, lonGrid, latGrid, Z, 18, 'LineStyle', 'none');
hold(ax, 'on');
scatter(ax, lonValid, latValid, 22, 'k', 'filled', 'MarkerFaceAlpha', 0.35);

cmap = [ ...
  0.95 1.00 1.00
  0.75 0.93 0.98
  0.45 0.78 0.93
  0.22 0.57 0.83
  0.08 0.33 0.68
  0.04 0.15 0.45
  ];
colormap(ax, interp1(linspace(0, 1, size(cmap, 1)), cmap, linspace(0, 1, 256)));

xlabel(ax, 'Longitude');
ylabel(ax, 'Latitude');
title(ax, sprintf('%d', thisYear), 'FontWeight', 'bold');
grid(ax, 'on');
axis(ax, 'tight');
end


function [availability, yearsVec] = buildMonthlyAvailability(dataTbl, startYear, endYear)
%BUILDMONTHLYAVAILABILITY Build month-year data presence matrix.
% Inputs:
%   dataTbl - monthly table containing year/month/rain_mm.
%   startYear, endYear - inclusive period limits.
% Output:
%   availability - 12 x N matrix (0 missing, 1 present).
%   yearsVec - year vector corresponding to matrix columns.

yearsVec = startYear:endYear;
availability = zeros(12, numel(yearsVec));

for i = 1:height(dataTbl)
  y = dataTbl.year(i);
  m = dataTbl.month(i);
  r = dataTbl.rain_mm(i);

  if y < startYear || y > endYear || isnan(m) || m < 1 || m > 12
    continue;
  end

  yPos = find(yearsVec == y, 1, 'first');
  if isempty(yPos)
    continue;
  end

  if ~isnan(r)
    availability(m, yPos) = 1;
  end
end
end


function annualTbl = aggregateAnnualStationYear(dataTbl, minMonthsPerYear)
%AGGREGATEANNUALSTATIONYEAR Aggregate monthly rainfall into annual station totals.
% Inputs:
%   dataTbl - monthly station records.
%   minMonthsPerYear - minimum valid months required to accept annual total.
% Output:
%   annualTbl - station-year table with annual_total and valid_months.

if isempty(dataTbl)
  annualTbl = table();
  return;
end

groups = findgroups(dataTbl.gauge_code, dataTbl.year);

validCount = splitapply(@(x) sum(~isnan(x)), dataTbl.rain_mm, groups);
rawSum = splitapply(@(x) sum(x, 'omitnan'), dataTbl.rain_mm, groups);
annualTotal = rawSum;

% Annual totals with poor monthly support are invalidated so trend tests and
% anomaly graphics are not driven by partial-year accumulation. The monthly
% values themselves are assumed to already satisfy the strict 10% missing-data
% tolerance from the preprocessing stage.
annualTotal(validCount < minMonthsPerYear) = NaN;

gauge = splitapply(@(x) x(1), dataTbl.gauge_code, groups);
year = splitapply(@(x) x(1), dataTbl.year, groups);
city = splitapply(@(x) x(1), dataTbl.city, groups);
state = splitapply(@(x) x(1), dataTbl.state, groups);
lat = splitapply(@(x) mean(x, 'omitnan'), dataTbl.lat, groups);
lon = splitapply(@(x) mean(x, 'omitnan'), dataTbl.lon, groups);

annualTbl = table(gauge, year, annualTotal, validCount, lat, lon, city, state, ...
  'VariableNames', {'gauge_code', 'year', 'annual_total', 'valid_months', 'lat', 'lon', 'city', 'state'});
end


function [tbl, sourcePath] = loadUnipluMonthlyData(matCandidates)
%LOADUNIPLUMONTHLYDATA Load first available MAT file and parse as table.
% Inputs:
%   matCandidates - ordered cell array of candidate MAT paths.
% Outputs:
%   tbl - parsed monthly table.
%   sourcePath - MAT file path used.

sourcePath = '';
raw = [];

for i = 1:numel(matCandidates)
  if isfile(matCandidates{i})
    raw = load(matCandidates{i});
    sourcePath = matCandidates{i};
    break;
  end
end

if isempty(sourcePath)
  error('MAT file not found. Expected dados_hidro_br_mensal_real.mat in standard paths.');
end

tbl = extractAsTable(raw);
if isempty(tbl) || ~istable(tbl)
  error('Could not parse dataset from MAT file: %s', sourcePath);
end
end


function tbl = extractAsTable(raw)
%EXTRACTASTABLE Parse multiple MAT storage layouts into a canonical table.
% Input:
%   raw - struct returned by MATLAB load().
% Output:
%   tbl - table with required columns.

required = {'gauge_code', 'year', 'month', 'rain_mm', 'lat', 'long', 'city', 'state'};
tbl = table();

if all(isfield(raw, required))
  tbl = table(raw.gauge_code, raw.year, raw.month, raw.rain_mm, raw.lat, raw.long, raw.city, raw.state, ...
    'VariableNames', required);
  return;
end

fields = fieldnames(raw);
for i = 1:numel(fields)
  obj = raw.(fields{i});

  if istable(obj) && all(ismember(required, obj.Properties.VariableNames))
    tbl = obj(:, required);
    return;
  end

  if isstruct(obj) && isscalar(obj) && all(isfield(obj, required))
    tbl = table(obj.gauge_code, obj.year, obj.month, obj.rain_mm, obj.lat, obj.long, obj.city, obj.state, ...
      'VariableNames', required);
    return;
  end

  if isstruct(obj) && all(ismember(required, fieldnames(obj)))
    tbl = struct2table(obj);
    tbl = tbl(:, required);
    return;
  end
end

if ~isempty(fields)
  firstObj = raw.(fields{1});
  if isstruct(firstObj) && isscalar(firstObj)
    nestedFields = fieldnames(firstObj);
    for j = 1:numel(nestedFields)
      nestedObj = firstObj.(nestedFields{j});
      if istable(nestedObj) && all(ismember(required, nestedObj.Properties.VariableNames))
        tbl = nestedObj(:, required);
        return;
      end
    end
  end
end
end


function outTbl = cleanInputTable(tbl)
%CLEANINPUTTABLE Standardize types, normalize text, and drop invalid rows.
% Input:
%   tbl - raw monthly table.
% Output:
%   outTbl - cleaned table with canonical lon column.

outTbl = tbl;

outTbl.gauge_code = normalizeText(toStringColumn(outTbl.gauge_code));
outTbl.city = normalizeText(toStringColumn(outTbl.city));
outTbl.state = normalizeText(toStringColumn(outTbl.state));

outTbl.year = toNumericColumn(outTbl.year);
outTbl.month = toNumericColumn(outTbl.month);
outTbl.rain_mm = toNumericColumn(outTbl.rain_mm);
outTbl.lat = toNumericColumn(outTbl.lat);
outTbl.lon = toNumericColumn(outTbl.long);

validRows = outTbl.gauge_code ~= "" & outTbl.state ~= "" & ...
  ~isnan(outTbl.year) & ~isnan(outTbl.month) & outTbl.month >= 1 & outTbl.month <= 12;

outTbl = outTbl(validRows, :);
outTbl = removevars(outTbl, 'long');
outTbl = sortrows(outTbl, {'state', 'gauge_code', 'year', 'month'});
end


function s = toStringColumn(x)
%TOSTRINGCOLUMN Convert heterogeneous vector input to string column.
if isstring(x)
  s = x(:);
elseif ischar(x)
  s = string(cellstr(x));
elseif iscell(x)
  s = strings(numel(x), 1);
  for i = 1:numel(x)
    s(i) = string(x{i});
  end
elseif isnumeric(x) || islogical(x)
  s = string(x(:));
else
  s = string(x);
  s = s(:);
end
end


function s = normalizeText(s)
%NORMALIZETEXT Normalize text for consistent filtering/grouping.
s = upper(strtrim(s));
s(ismissing(s)) = "";
end


function n = toNumericColumn(x)
%TONUMERICCOLUMN Convert heterogeneous vector input to numeric column.
if isnumeric(x) || islogical(x)
  n = double(x(:));
elseif isstring(x)
  n = str2double(x(:));
elseif ischar(x)
  n = str2double(string(cellstr(x)));
elseif iscell(x)
  n = nan(numel(x), 1);
  for i = 1:numel(x)
    n(i) = str2double(string(x{i}));
  end
else
  n = str2double(string(x));
  n = n(:);
end
end


function [pValue, senSlope, trendLabel] = runKtaubSafe(years, values)
%RUNKTAUBSAFE Execute Mann-Kendall test safely with graceful fallback.
% Inputs:
%   years, values - aligned annual vectors.
% Outputs:
%   pValue - significance value returned by ktaub.
%   senSlope - Sen's slope estimator (mm/year).
%   trendLabel - textual trend interpretation.

pValue = NaN;
senSlope = NaN;
trendLabel = 'No significant trend';

if numel(values) < 3 || numel(years) ~= numel(values)
  return;
end

alpha = 0.05;
datain = [years(:), values(:)];

try
  [~, ~, h, sig, ~, ~, ~, sen] = ktaub(datain, alpha, 0);
  pValue = sig;
  senSlope = sen;
  trendLabel = mkTrendLabel(h, senSlope);
catch
  trendLabel = 'ktaub not available/incompatible';
end
end


function t = mkTrendLabel(h, senSlope)
%MKTRENDLABEL Convert Mann-Kendall decision into human-readable text.
if isnumeric(h) && h == 1
  if isfinite(senSlope) && senSlope > 0
    t = 'Increasing trend';
  elseif isfinite(senSlope) && senSlope < 0
    t = 'Decreasing trend';
  else
    t = 'Significant trend';
  end
else
  t = 'No significant trend';
end
end


function txt = formatMetric(v)
%FORMATMETRIC Format numeric metric for report text.
if isempty(v) || ~isfinite(v)
  txt = 'n/a';
else
  txt = sprintf('%.3f', v);
end
end
